### ISSUE TITLE
Success callback never get called

### ISSUE THREAD

**Issue by sktniranjan** [nickbarth/cordova.phonegap.audio.encode#1]
HI,
      Thank you for this plugin. I have tried to use your plugin in my project. But the success callback never getting call. 

```
NSLog(@"Arg URL=%@",audioPath);
NSLog(@"Audio URL=%@",audioURL);
NSLog(@"Export URL=%@",exportURL);
NSLog(@"Destination URL=%@",destinationURL);
```

It displays above all URL, but not get into success callback. Any idea?

**Comment by sktniranjan** [comment]
I got null value for Audio URL. So i changed like this

 //NSURL\* audioURL = [NSURL URLWithString:audioPath];    // old

   NSURL\* audioURL = [NSURL fileURLWithPath:audioPath]; //new

Now its working fine.

**Comment by nickbarth** [comment]
Hmm! I'll try it out and update that. Thanks sktniranjan.
